apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whatever
spec:
  rules:
  - host: whatever.A.B.C.D.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: whatever
          servicePort: 1234
